### ISSUE TITLE
Regenerate test files

### ISSUE THREAD

**Issue by andypbarrett** [ICESAT-2HackWeek/h5cloud#20]
As part of housekeeping, the test files in the S3 bucket were deleted.  These files need to be regenerated and stored in a bucket that is persistent.  See https://icesat2hackweek.slack.com/archives/C05LQQS1JQ2/p1695828721176839

I'm thinking it would be helpful to have a file generation script to facilitate regenerating these files, and to generate files for other regions.

**Comment by asteiker** [comment]
From @betolink : We now have the same files we used for our benchmarks in the following buckets:

s3://nasa-cryo-persistent/h5cloud/atl03/  - CryoCloud account (accessible only from CryoCloud Hub)
NSIDC bucket: 
- s3://is2-cloud-experiments/h5cloud/atl03 (publicly accessible in us-west-2; direct S3 only access)
- This is more of a backup, but there are some issues with env variables when accessing from, e.g. 2i2c Openscapes Hub

They are under "big" since they are big files for IS2 standards, there is another directory "average" where granules are approx 500MB from Region 1.

@betolink will update https://github.com/ICESAT-2HackWeek/h5cloud/blob/main/notebooks/01_data-selection.ipynb with Region 1 search parameters to complete this Issue.

**Comment by asteiker** [comment]
See https://github.com/ICESAT-2HackWeek/h5cloud/commit/8f6244c5593032012da474d8ba57c4b2eab8b01b for updated notebook
